/**
  ******************************************************************************
  * @file    html.h
  * @author  Waveshare Team
  * @version V1.0.0
  * @date    23-January-2018
  * @brief   This file describes the sending of HTML-page to a client
  *
  ******************************************************************************
  */
extern  ESP8266WebServer server;
extern  IPAddress myIP;      

void handleRoot()
{
server.send(200, F("text/html"), 
"<!DOCTYPE html>\r\n"
"<html>\r\n"
"<head>\r\n"
"<meta charset='utf-8'>\r\n"
"<title>E-paper Logik</title>\r\n"
"<link rel='stylesheet' href='styles.css'>\r\n"
"<script src='processingA.js'></script>\r\n"
"<script src='processingB.js'></script>\r\n"
"<script src='processingC.js'></script>\r\n"
"<script src='processingD.js'></script>\r\n"
"</head>\r\n"
"<body>\r\n"
"<div class='header_back'>\r\n"
"<div class='header_face'></div>\r\n"
"</div>\r\n"
"<div class='content_back'>\r\n"
"<div class='content_face'>\r\n"
"<table style='width:100%; height:100%' border='0' cellspacing='0'>\r\n"
"<tr>\r\n"
"<td class='menu_bar' rowspan='2'>\r\n"
"<div id='BT'></div>\r\n"
"<table>\r\n"
"<tr>\r\n"
"<td class='comment' colspan='4'><br>Device IP:</td>\r\n"
"</tr>\r\n"               
"<tr>\r\n"
"<td colspan=\"4\"><input id=\"ip_addr\" style=\"width:100%;text-align:center\" type=\"text\" value=\"\r\n"
+ String(myIP[0],DEC)+'.'+String(myIP[1],DEC)+'.'+String(myIP[2],DEC)+'.'+String(myIP[3],DEC)+F("\"></td>\r\n"
"</tr>\r\n"               
"<tr><td class='comment' colspan='4'><br>Bounds:</td></tr>\r\n" 
"<tr id='XY'></tr>\r\n"
"<tr id='WH'></tr>\r\n"
"</table>\r\n"       
"<div id='RB'></div>\r\n"
"</td>\r\n"
"<td class='content_body'>\r\n"
"<span class='title'>Original image</span><br>\r\n"
"<canvas id='source' class='hidden_input'></canvas>\r\n"        
"<div id='srcBox'>\r\n"
"<div class='imgBox'>\r\n"
"<div class='mesBox'>Drop image here...</div>\r\n"
"</div>\r\n"
"</div>\r\n"            
"</td>\r\n"      
"</tr>\r\n"
"<tr>\r\n"
"<td id='dstBox' class='content_body'>\r\n" 
"</td>\r\n"  
"<td id='dstClock' class='content_body'>\r\n"
"<canvas id=\"clockcanvas\" width=\"400\" height=\"300\"\r\n"
"style=\"background-color:#999\">\r\n"
"</canvas>\r\n"
"<script>\r\n"
"var canvas = document.getElementById(\"clockcanvas\");\r\n"
"var ctx = canvas.getContext(\"2d\");\r\n"
"var radius = canvas.height / 2;\r\n"
"ctx.translate(radius, radius);\r\n"
"radius = radius * 0.90\r\n"
"setInterval(drawClock, 1000);\r\n"
"function drawClock() {\r\n"
"drawFace(ctx, radius);\r\n"
"drawNumbers(ctx, radius);\r\n"
"drawTime(ctx, radius);\r\n"
"}\r\n"
"function drawFace(ctx, radius) {\r\n"
"var grad;\r\n"
"ctx.beginPath();\r\n"
"ctx.arc(0, 0, radius, 0, 2*Math.PI);\r\n"
"ctx.fillStyle = 'white';\r\n"
"ctx.fill();\r\n"
"grad = ctx.createRadialGradient(0,0,radius*0.95, 0,0,radius*1.05);\r\n"
"grad.addColorStop(0, '#333');\r\n"
"grad.addColorStop(0.5, 'white');\r\n"
"grad.addColorStop(1, '#333');\r\n"
"ctx.strokeStyle = grad;\r\n"
"ctx.lineWidth = radius*0.1;\r\n"
"ctx.stroke();\r\n"
"ctx.beginPath();\r\n"
"ctx.arc(0, 0, radius*0.1, 0, 2*Math.PI);\r\n"
"ctx.fillStyle = '#333';\r\n"
"ctx.fill();\r\n"
"}\r\n"
"function drawNumbers(ctx, radius) {\r\n"
"var ang;\r\n"
"var num;\r\n"
"ctx.font = radius*0.15 + \"px arial\";\r\n"
"ctx.textBaseline=\"middle\";\r\n"
"ctx.textAlign=\"center\";\r\n"
"for(num = 1; num < 13; num++){\r\n"
"ang = num * Math.PI / 6;\r\n"
"ctx.rotate(ang);\r\n"
"ctx.translate(0, -radius*0.85);\r\n"
"ctx.rotate(-ang);\r\n"
"ctx.fillText(num.toString(), 0, 0);\r\n"
"ctx.rotate(ang);\r\n"
"ctx.translate(0, radius*0.85);\r\n"
"ctx.rotate(-ang);\r\n"
"}\r\n"
"}\r\n"
"function drawTime(ctx, radius){\r\n"
"var now = new Date();\r\n"
"var hour = now.getHours();\r\n"
"var minute = now.getMinutes();\r\n"
"var second = now.getSeconds();\r\n"
"//hour\r\n"
"hour=hour%12;\r\n"
"hour=(hour*Math.PI/6)+\r\n"
"(minute*Math.PI/(6*60))+\r\n"
"(second*Math.PI/(360*60));\r\n"
"drawHand(ctx, hour, radius*0.5, radius*0.07);\r\n"
"//minute\r\n"
"minute=(minute*Math.PI/30)+(second*Math.PI/(30*60));\r\n"
"drawHand(ctx, minute, radius*0.8, radius*0.07);\r\n"
"// second\r\n"
"second=(second*Math.PI/30);\r\n"
"drawHand(ctx, second, radius*0.9, radius*0.02);\r\n"
"}\r\n"
"function drawHand(ctx, pos, length, width) {\r\n"
"ctx.beginPath();\r\n"
"ctx.lineWidth = width;\r\n"
"ctx.lineCap = \"round\";\r\n"
"ctx.moveTo(0,0);\r\n"
"ctx.rotate(pos);\r\n"
"ctx.lineTo(0, -length);\r\n"
"ctx.stroke();\r\n"
"ctx.rotate(-pos);\r\n"
"}\r\n"
"</script>\r\n"
"</td>\r\n"      
"</tr>\r\n"
"</table>\r\n"
"</div>\r\n"
"</div>\r\n"
"<div class='footer_back'>\r\n"
"<div class='footer_face' id='logTag'>\r\n"
"</div>\r\n"
"</div>\r\n"
"</body>\r\n"
"</html>\r\n"));
}
